openapi: 3.0.0
info:
  title: Product Service API
  version: 1.0.0
servers:
  - url: https://7ntmtglg2b.execute-api.eu-north-1.amazonaws.com/prod/
paths:
  /products:
    get:
      summary: Get the list of products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{productId}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: The ID of the product to retrieve
      responses:
        '200':
          description: A product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        price:
          type: number
          format: float
